<!DOCTYPE html>
<html  class="post-bgc">
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Midterm Project</title>
	<link rel="stylesheet" href="css/styles.css">
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
	<link href="https://fonts.googleapis.com/css?family=La+Belle+Aurore|Raleway&display=swap" rel="stylesheet">

</head>

<header>
  <a class="logo" href="index.html">Dominique Dorvil</a>
  
  <input id="nav" type="checkbox">
  <label for="nav"></label>
  
  <?php include "inc/nav.inc"; ?>
  
</header>